### PR TITLE
Merge the upstream v0.10.0 rukpak tag

### PR DESCRIPTION
**Pull request by timflannagan**
Merges the v0.10.0 upstream tag + individual cherry picks that need to be present downstream.

### CODE REVIEW

**Comment by timflannagan** [comment]
We're still waiting to be introduced into the payload so adding the requisite labels until then.

/label docs-approved
/label px-approved
/label qe-approved

**Comment by timflannagan** [comment]
Just want to double check these changes on a clusterbot cluster.

/hold

**Comment by tylerslaton** [comment]
@timflannagan Hm, that's weird. I checked in the container and it seems to contain the cp exectuable. 

```
$ docker run -it registry.ci.openshift.org/ocp/4.12:base cp --version
cp (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.
```

**Pull request merged**
