### PR TITLE
[WIP] AUTH-482: set required-scc for openshift workloads

### PR DESCRIPTION
**Pull request by kramaranya**
[AUTH-482](https://issues.redhat.com/browse/AUTH-482)

### CODE REVIEW

**Comment by kramaranya** [comment]
I was unable to verify if the changes were applied using must-gather from CI jobs, as there is no namespace called `openshift-rukpak`. Is there any other test or method I could use to see if the annotations were applied correctly?

**Comment by kevinrizza** [comment]
We pulled this component from the payload completely -- at the time we did that, it was still tech preview -- and we no longer have plans to ever release it into openshift by default. The repo will remain open for now to ensure that previous releases can still be built, but I think this pull request is no longer necessary.

**Comment by kramaranya** [comment]
@kevinrizza thank you for the update. I noticed that this namespace no longer appears in the failing tests in Sippy, which is why I had moved the PR to WIP. Since the component is no longer planned for release, these changes are no longer necessary. Please let me know if there's any need to keep this PR active - otherwise, I'm happy to close the PR.

**Pull request closed without merging**
