### PR TITLE
[release-4.12]: OCPBUGS-27593,OCPBUGS-27678: Update go-git to v5.11.0

### PR DESCRIPTION
**Pull request by kevinrizza**
Manual cherry pick

### CODE REVIEW

**Comment by m1kola** [comment]
/retest

I'll try to re-test, but it looks like the issue is not a flake.

```
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package trace: could not load export data: no export data for \"github.com/go-git/go-git/v5/utils/trace\"\n\n"
```

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Pull request merged**
