### PR TITLE
[release-4.15]: OCPBUGS-30264: Bump Helm & K8s dependencies

### PR DESCRIPTION
**Pull request by m1kola**
Manual cherry pick.

There are two commits: one contains `go mod vendor` and another actual changes.

### CODE REVIEW

**Comment by m1kola** [comment]
Putting on hold until I sort out Jira tickets.

/hold

**Comment by m1kola** [comment]
/retitle [release-4.15]: OCPBUGS-30264: Bump Helm & K8s dependencies

**Review by varshaprasad96 — APPROVED** [review]
Thanks for fixing this @m1kola :))

/lgtm
/approve

**Comment by m1kola** [comment]
/unhold

Jira tickets are now in good order.

**Pull request merged**
